#############################################################################
# Makefile for building: othello
# Generated by qmake (1.03a) on: Tue May 20 13:18:23 2003
# Project:  othello.pro
# Template: app
# Command: $(QMAKE) othello.pro
#############################################################################

####### Compiler, tools and options

CC       = gcc
CXX      = g++
LEX      = flex
YACC     = yacc
CFLAGS   = -pipe -Wall -W -O2  -DQT_NO_DEBUG
CXXFLAGS = -pipe -Wall -W -O2  -DQT_NO_DEBUG
LEXFLAGS = 
YACCFLAGS= -d
INCPATH  = -I$(QTDIR)/include -I$(QTDIR)/mkspecs/default
LINK     = g++
LFLAGS   = 
LIBS     = $(SUBLIBS)  -Wl,-rpath,$(QTDIR)/lib  -L$(QTDIR)/lib  -L/usr/X11R6/lib -lqt -lXext -lX11 -lm
AR       = ar cqs
RANLIB   = 
MOC      = $(QTDIR)/bin/moc
UIC      = $(QTDIR)/bin/uic
QMAKE    = qmake
TAR      = tar -cf
GZIP     = gzip -9f
COPY     = cp -f
COPY_FILE= $(COPY) -p
COPY_DIR = $(COPY) -pR
DEL_FILE = rm -f
SYMLINK  = ln -sf
DEL_DIR  = rmdir
MOVE     = mv

####### Output directory

OBJECTS_DIR = ./

####### Files

HEADERS = ai.h \
		aiplayer.h \
		animpiece.h \
		board.h \
		boardview.h \
		gamerules.h \
		othello.h \
		piece.h \
		playerif.h \
		rules.h
SOURCES = ai.cpp \
		aiplayer.cpp \
		animpiece.cpp \
		board.cpp \
		boardview.cpp \
		gamerules.cpp \
		main.cpp \
		othello.cpp \
		piece.cpp \
		rules.cpp
OBJECTS = ai.o \
		aiplayer.o \
		animpiece.o \
		board.o \
		boardview.o \
		gamerules.o \
		main.o \
		othello.o \
		piece.o \
		rules.o
FORMS = 
UICDECLS = 
UICIMPLS = 
SRCMOC   = moc_aiplayer.cpp \
		moc_animpiece.cpp \
		moc_boardview.cpp \
		moc_othello.cpp \
		moc_playerif.cpp
OBJMOC = moc_aiplayer.o \
		moc_animpiece.o \
		moc_boardview.o \
		moc_othello.o \
		moc_playerif.o
DIST	   = othello.pro
QMAKE_TARGET = othello
DESTDIR  = 
TARGET   = othello

first: all
####### Implicit rules

.SUFFIXES: .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o $@ $<

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o $@ $<

####### Build rules

all: Makefile $(TARGET)

$(TARGET): $(UICDECLS) $(OBJECTS) $(OBJMOC) 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJMOC) $(LIBS)

mocables: $(SRCMOC)

$(MOC): 
	( cd $(QTDIR)/src/moc ; $(MAKE) )

Makefile: othello.pro  $(QTDIR)/mkspecs/default/qmake.conf 
	$(QMAKE) othello.pro
qmake: 
	@$(QMAKE) othello.pro

dist: 
	@mkdir -p .tmp/othello && $(COPY_FILE) --parents $(SOURCES) $(HEADERS) $(FORMS) $(DIST) .tmp/othello/ && ( cd `dirname .tmp/othello` && $(TAR) othello.tar othello && $(GZIP) othello.tar ) && $(MOVE) `dirname .tmp/othello`/othello.tar.gz . && $(DEL_DIR) .tmp/othello

mocclean:
	-$(DEL_FILE) $(OBJMOC)
	-$(DEL_FILE) $(SRCMOC)

uiclean:

clean: mocclean
	-$(DEL_FILE) $(OBJECTS) 
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) $(TARGET)


FORCE:

####### Compile

ai.o: ai.cpp ai.h \
		rules.h \
		board.h

aiplayer.o: aiplayer.cpp aiplayer.h \
		gamerules.h \
		ai.h \
		playerif.h \
		rules.h \
		board.h

animpiece.o: animpiece.cpp animpiece.h \
		piece.h

board.o: board.cpp board.h

boardview.o: boardview.cpp boardview.h \
		piece.h \
		animpiece.h \
		gamerules.h \
		aiplayer.h \
		rules.h \
		board.h \
		playerif.h

gamerules.o: gamerules.cpp gamerules.h \
		rules.h \
		board.h

main.o: main.cpp othello.h \
		piece.h \
		animpiece.h

othello.o: othello.cpp othello.h \
		animpiece.h \
		piece.h \
		boardview.h \
		gamerules.h \
		rules.h \
		board.h

piece.o: piece.cpp piece.h

rules.o: rules.cpp rules.h \
		board.h

moc_aiplayer.o: moc_aiplayer.cpp aiplayer.h playerif.h

moc_animpiece.o: moc_animpiece.cpp animpiece.h piece.h

moc_boardview.o: moc_boardview.cpp boardview.h gamerules.h \
		rules.h \
		board.h

moc_othello.o: moc_othello.cpp othello.h piece.h \
		animpiece.h

moc_playerif.o: moc_playerif.cpp playerif.h 

moc_aiplayer.cpp: $(MOC) aiplayer.h
	$(MOC) aiplayer.h -o moc_aiplayer.cpp

moc_animpiece.cpp: $(MOC) animpiece.h
	$(MOC) animpiece.h -o moc_animpiece.cpp

moc_boardview.cpp: $(MOC) boardview.h
	$(MOC) boardview.h -o moc_boardview.cpp

moc_othello.cpp: $(MOC) othello.h
	$(MOC) othello.h -o moc_othello.cpp

moc_playerif.cpp: $(MOC) playerif.h
	$(MOC) playerif.h -o moc_playerif.cpp

####### Install

install: all 

uninstall: 

